services:
  db:
    image: mysql:8.4
    container_name: festivo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-festivo}
      MYSQL_USER: ${MYSQL_USER:-festivo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-festivo}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-festivo_root}
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - festivo-db-data:/var/lib/mysql
      - ../scripts/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "set -e; mysqladmin --protocol=TCP ping -h 127.0.0.1 -uroot --password=\"$$MYSQL_ROOT_PASSWORD\" --silent"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: festivo-keycloak
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HTTP_PORT: 8081
      KC_HOSTNAME: localhost
      KC_HOSTNAME_URL: ${KEYCLOAK_FRONTEND_URL:-http://localhost:8081}
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8081:8081"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ../backend
    container_name: festivo-backend
    restart: unless-stopped
    env_file: .env.example
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://db:3306/festivo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-festivo}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-festivo}
      OIDC_ISSUER_URI: ${OIDC_ISSUER_URI:-http://keycloak:8081/realms/festivo}
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
    container_name: festivo-frontend
    restart: unless-stopped
    env_file: .env.example
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost/api}
      VITE_OIDC_AUTH_URL: ${VITE_OIDC_AUTH_URL:-http://localhost:8081/realms/festivo}
      VITE_OIDC_CLIENT_ID: ${VITE_OIDC_CLIENT_ID:-festivo-web}
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:5173"

  nginx:
    image: nginx:1.25
    container_name: festivo-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

volumes:
  festivo-db-data:
