spring:
  application:
    name: festivo-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/festivo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:festivo}
    password: ${SPRING_DATASOURCE_PASSWORD:festivo}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    time-zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://keycloak:8081/realms/festivo}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

festivo:
  payhere:
    base-url: ${PAYHERE_BASE_URL:https://sandbox.payhere.lk}
    merchant-id: ${PAYHERE_MERCHANT_ID:demo}
    merchant-secret: ${PAYHERE_MERCHANT_SECRET:demo}
    notify-url: ${PAYHERE_NOTIFY_URL:http://localhost/api/payments/callback}
  messaging:
    firebase-enabled: ${FIREBASE_EMULATOR_ENABLED:false}

logging:
  level:
    org.springframework.security: INFO
